name: Haskell CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: [3.6.2.0]
        ghc: [9.0.1, 8.10.7]
    env:
      CONFIG: '--enable-tests --enable-benchmarks'
    steps:
      - uses: actions/checkout@v2
      - name: Haskell Setup
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '${{ matrix.ghc }}'
          cabal-version: '${{ matrix.cabal }}'
      - name: Update Dependencies
        run: cabal update
      - name: Freeze Dependencies
        run: cabal freeze $CONFIG
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - name: Build
        run: cabal build $CONFIG
      - name: Test
        run: cabal test $CONFIG
